#!/bin/bash
#
# Install local JARs to Maven local repository
# Generated by ant2maven migration tool
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "Installing local JARs to Maven repository..."

<#list internalJars as jar>
echo "Installing ${jar.name}..."
mvn install:install-file \
    -Dfile="${jar.name}" \
    -DgroupId="${jar.groupId}" \
    -DartifactId="${jar.artifactId}" \
    -Dversion="${jar.version}" \
    -Dpackaging=jar \
    -DgeneratePom=true

</#list>
echo "Done! All local JARs have been installed."
