#!/bin/bash
#
# Install local JARs to Maven local repository
# Generated by ant2maven migration tool
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo "Installation des JARs dans le repository Maven local du projet..."

<#list internalJars as jar>
echo "Installing ${jar.name}..."
./mvnw -s .mvn/wrapper/settings.xml install:install-file \
    -Dfile="liblocale/${jar.name}" \
    -DgroupId="${jar.groupId}" \
    -DartifactId="${jar.artifactId}" \
    -Dversion="${jar.version}" \
    -Dpackaging=jar \
    -DgeneratePom=true

</#list>
echo "Terminé ! ${internalJars?size} JARs installés."
